export const TRUST_METRICS = [
    { value: "6개", label: "정량 분석 기반 프로젝트" },
    { value: "1,652 PR", label: "단일 사례 최대 협업 규모" },
    { value: "6개 플랫폼", label: "최대 멀티플랫폼 지원 범위" },
    { value: "5개 산업", label: "핀테크 · 헬스케어 · AI · 글로벌 · Web3" },
];

export const PROJECTS = [
    {
        slug: "series-b",
        titleKo: "시리즈비",
        titleEn: "Series B",
        tagline: "투자조합 관리 · 업무 자동화 올인원 플랫폼",
        sector: "핀테크 / 투자조합 SaaS",
        market: "대한민국",
        summary: "GP·LP·스타트업을 연결하는 투자 라이프사이클 플랫폼으로, 결재·규제 보고·문서 협업·펀드 운영을 하나의 서비스에 통합했습니다.",
        problem: "벤처캐피탈 운영 현장은 엑셀, 이메일, 수기 보고, 분산된 결재 시스템 때문에 운영 속도와 규제 대응 품질이 동시에 떨어지는 구조였습니다.",
        solution: "Next.js·NestJS 기반 플랫폼 안에 한국형 전자결재, VICS 자동화, 실시간 공동 편집, AI 투자심사보고서 생성을 묶어 GP와 LP가 하나의 운영 흐름에서 일할 수 있도록 재설계했습니다.",
        impactMetrics: [
            { value: "1,652건", label: "총 PR" },
            { value: "179개", label: "DB 마이그레이션" },
            { value: "22개", label: "백엔드 도메인 모듈" },
        ],
        stack: ["Next.js", "NestJS", "MySQL", "Yjs CRDT", "CloudFormation", "ChatGPT API"],
        strengths: ["VICS 규제 보고 자동화", "실시간 문서 공동 편집", "5중 보안 아키텍처"],
        status: "completed",
        publicLinks: [],
        featured: true,
    },
    {
        slug: "ez-approve",
        titleKo: "이지어프루브",
        titleEn: "EZ-Approve",
        tagline: "투자조합 전자결재 · 펀드관리 올인원 플랫폼",
        sector: "엔터프라이즈 워크플로우 / 핀테크",
        market: "대한민국",
        summary: "VC 운용사를 위한 전자결재와 펀드 관리를 짧은 기간 안에 구축한 고밀도 제품으로, 한국형 결재 문화와 규제 흐름을 서비스 안에 내재화했습니다.",
        problem: "기존 VC 업무는 범용 그룹웨어와 개별 문서 시스템에 흩어져 있었고, 결재와 펀드 문서 흐름이 실시간 협업과 연결되지 못했습니다.",
        solution: "다단계 전자결재, GP/LP 펀드 관리, CRDT 기반 실시간 편집, 전자도장, NICE 인증 연계를 단일 SaaS로 결합해 빠른 의사결정과 규정 준수를 동시에 지원했습니다.",
        impactMetrics: [
            { value: "504건", label: "9주간 총 PR" },
            { value: "50+개", label: "프론트엔드 페이지" },
            { value: "5종", label: "VICS 규제 양식" },
        ],
        stack: ["Next.js", "NestJS", "MySQL", "Lexical", "Yjs", "NICE KYC"],
        strengths: ["다우오피스급 결재 엔진", "9주 고속 구축", "한국형 인증·알림 연동"],
        status: "active",
        publicLinks: [],
        featured: true,
    },
    {
        slug: "harmony-link",
        titleKo: "하모니 링크",
        titleEn: "Harmony Link",
        tagline: "노인 주간보호센터 통합 관리 플랫폼",
        sector: "헬스케어 / 돌봄 운영",
        market: "대한민국",
        summary: "종사자, 어르신, 보호자, 관리자가 하나의 제품 안에서 연결되는 돌봄 운영 플랫폼으로, 기록·투약·알림·건강 분석을 통합했습니다.",
        problem: "돌봄 현장은 종이 기록, 분산된 연락 수단, 제한된 관리자 시야 때문에 운영 품질과 보호자 신뢰를 동시에 확보하기 어려웠습니다.",
        solution: "Flutter 멀티플랫폼 앱과 관리자 웹, NestJS 백엔드, AI 건강 분석을 결합해 시설 운영과 보호자 커뮤니케이션을 한 흐름으로 묶었습니다.",
        impactMetrics: [
            { value: "133,000+", label: "총 LOC" },
            { value: "140+", label: "API 엔드포인트" },
            { value: "6개", label: "지원 플랫폼" },
        ],
        stack: ["Flutter", "Next.js", "NestJS", "MySQL", "AWS CDK", "OpenAI"],
        strengths: ["AI 건강 분석 내장", "6개 플랫폼 단일 운영", "AWS IaC 기반 배포"],
        status: "completed",
        publicLinks: [],
        featured: true,
    },
    {
        slug: "ai-agent",
        titleKo: "AI-Native Development Framework",
        titleEn: "AI-Native Development Framework",
        tagline: "다중 AI 에이전트 통합 개발 운영 프레임워크",
        sector: "AI 개발 자동화 / DevOps",
        market: "글로벌",
        summary: "Claude, Gemini, Codex, Jules를 하나의 운영 계층에서 다루는 다중 에이전트 프레임워크로, 기획부터 검증까지의 SDLC를 자동화합니다.",
        problem: "AI 도구별 워크플로우가 분절되어 있고 품질 기준이 일관되지 않아, 팀 차원의 신뢰 가능한 운영 체계를 만들기 어려웠습니다.",
        solution: "에이전트 독립형 오케스트레이션, Knowledge-as-Code, 12개 품질 게이트, 실시간 대시보드를 결합해 AI 기반 개발을 운영 체계로 전환했습니다.",
        impactMetrics: [
            { value: "839개", label: "지식 문서" },
            { value: "134+개", label: "재사용 스킬" },
            { value: "12개", label: "자동 품질 게이트" },
        ],
        stack: ["TypeScript", "React 19", "Hono", "PostgreSQL", "Prisma", "Playwright"],
        strengths: ["멀티 AI 공급자 통합", "위변조 감지 품질 게이트", "실시간 대시보드"],
        status: "active",
        publicLinks: [],
        featured: false,
    },
    {
        slug: "connectin",
        titleKo: "커넥틴",
        titleEn: "Connectin",
        tagline: "디지털 명함 & 프로페셔널 네트워킹 플랫폼",
        sector: "글로벌 네트워킹 / 모바일 서비스",
        market: "베트남",
        summary: "OCR 명함 스캔, BLE/GPS 근거리 탐색, E2E 암호화 메시징을 결합한 비즈니스 네트워킹 서비스입니다.",
        problem: "오프라인 명함 교환과 온라인 네트워킹 사이의 간극이 컸고, 베트남 현지 시장에 최적화된 보안형 비즈니스 네트워킹 제품이 부족했습니다.",
        solution: "Flutter 앱, Next.js 웹, 마이크로서비스 백엔드, Zalo 연계를 통해 물리적 명함 문화와 디지털 네트워킹을 자연스럽게 이어 붙였습니다.",
        impactMetrics: [
            { value: "12개", label: "독립 마이크로서비스" },
            { value: "41개", label: "모바일 기능 모듈" },
            { value: "3개", label: "지원 플랫폼" },
        ],
        stack: ["Flutter", "Next.js", "Express.js", "PostgreSQL", "Signal Protocol", "Firebase"],
        strengths: ["Signal Protocol E2E 암호화", "BLE + GPS 탐색", "Zalo 현지화 통합"],
        status: "dormant",
        publicLinks: [],
        featured: false,
    },
    {
        slug: "life3",
        titleKo: "라이프3 / 데이스타터",
        titleEn: "Life3 / DayStarter",
        tagline: "Web 3.0 dApp 마켓플레이스 · 리워드 게임 생태계",
        sector: "Web3 / 게이미피케이션",
        market: "글로벌",
        summary: "NFT 마켓플레이스, 포인트-토큰 스왑, AI 운세 게임, 에어드롭 운영을 하나의 Web3 제품 안에 통합한 dApp 플랫폼입니다.",
        problem: "블록체인 제품은 사용자 경험이 복잡하고, 게임 보상 구조와 자산 정합성을 함께 만족시키기 어려워 대중적 진입 장벽이 높았습니다.",
        solution: "4개 마이크로서비스, Kafka 이벤트 흐름, 복식부기 원장, AWS KMS 기반 서명 구조를 통해 Web3 UX와 자산 안정성을 동시에 확보했습니다.",
        impactMetrics: [
            { value: "4개", label: "마이크로서비스" },
            { value: "~98개", label: "Sequelize 모델" },
            { value: "3개", label: "Ethereum 스마트 컨트랙트" },
        ],
        stack: ["React", "Next.js", "Express.js", "PostgreSQL", "Kafka", "AWS KMS"],
        strengths: ["복식부기 토큰 회계", "GPT-4o 기반 운세 게임", "KMS 지갑 서명 아키텍처"],
        status: "completed",
        publicLinks: [],
        featured: false,
    },
];
