export const PROJECTS = [
    {
        slug: "series-b",
        titleKo: "시리즈비",
        titleEn: "Series B",
        tagline: "투자조합 관리와 규제 보고를 하나로 묶은 한국형 핀테크 플랫폼",
        sector: "핀테크",
        market: "한국",
        period: "2023.11 - 2024.12",
        status: "구축 완료",
        featured: true,
        summary: "투자조합 운영, 협업 문서, VICS 보고, KYC, 보안 권한을 단일 업무 흐름으로 통합한 B2B SaaS입니다.",
        challenge: "투자심사와 조합 운영은 문서, 결재, 규제 보고, 협업 편집이 분절되기 쉬워 운영 비용과 오류 가능성이 높습니다.",
        approach: "Next.js와 NestJS 기반으로 투자 업무 전체를 하나의 제품 흐름으로 연결하고, PDF 파이프라인과 CRDT 협업, AI 리포트 생성까지 운영 구조 안에 묶었습니다.",
        impactMetrics: ["1,652건 총 PR", "179개 DB 마이그레이션", "55+ API 컨트롤러"],
        stack: ["Next.js", "React", "NestJS", "MySQL", "CloudFormation", "OCR"],
        highlights: ["5종 VICS 규제 양식 자동화", "실시간 협업 편집 구조", "투자조합 운영과 문서 워크플로우 일체화"],
        evidenceNote: "지표는 market-intel 코드베이스 분석과 원페이저 자산 기준으로 정리했습니다."
    },
    {
        slug: "ez-approve",
        titleKo: "이지어프루브",
        titleEn: "EZ-Approve",
        tagline: "전자결재와 펀드 운영 실무를 압축 구현한 승인 플랫폼",
        sector: "핀테크",
        market: "한국",
        period: "2026.01 - 2026.03",
        status: "활성 개발",
        featured: true,
        summary: "전자결재, 규제 대응, 협업 편집을 빠른 주기로 압축 구현한 투자조합용 승인 플랫폼입니다.",
        challenge: "짧은 기간 안에 다우오피스급 전자결재 경험과 한국 VC 업무 특화 흐름을 동시에 맞춰야 했습니다.",
        approach: "작은 팀 구성을 전제로 화면, 결재 엔진, 협업 편집, 권한 구조를 고밀도로 설계해 9주 안에 핵심 범위를 구현했습니다.",
        impactMetrics: ["504건 9주간 총 PR", "50+ 프론트 페이지", "5종 VICS 양식"],
        stack: ["Next.js", "React", "NestJS", "MySQL", "Lexical", "Yjs"],
        highlights: ["실시간 협업 편집", "5계층 보안 구조", "펀드관리와 결재 엔진의 통합"],
        evidenceNote: "지표는 catalog와 case-study 기준이며 공개 가능한 범위만 사용했습니다."
    },
    {
        slug: "harmony-link",
        titleKo: "하모니 링크",
        titleEn: "Harmony Link",
        tagline: "시니어 케어 운영을 6개 플랫폼으로 연결한 헬스케어 서비스",
        sector: "헬스케어",
        market: "한국",
        period: "6개월",
        status: "구축 완료",
        featured: true,
        summary: "센터, 보호자, 기사, 관리자, 모바일 앱과 웹 어드민까지 연결한 시니어 데이케어 운영 플랫폼입니다.",
        challenge: "현장 운영과 보호자 경험, 배차와 약 복용 관리, 권한 체계를 동시에 다뤄야 하는 멀티액터 서비스였습니다.",
        approach: "Flutter, NestJS, Next.js를 조합한 멀티레포 구조로 앱과 관리자 경험을 함께 설계하고, AI 건강 분석과 인프라 자동화까지 포함했습니다.",
        impactMetrics: ["133,000+ LOC", "140+ API", "6개 플랫폼"],
        stack: ["Flutter", "NestJS", "Next.js", "MySQL", "AWS CDK", "OpenAI"],
        highlights: ["시니어 케어 운영 전용 워크플로우", "AI 건강 분석 연동", "AWS CDK 기반 인프라 코드화"],
        evidenceNote: "헬스케어 도메인 지표는 catalog와 내부 분석 문서의 공통 수치만 사용했습니다."
    },
    {
        slug: "p2p-funding",
        titleKo: "P2P 크라우드 펀딩 플랫폼",
        titleEn: "P2P Funding",
        tagline: "대출, 투자, 심사를 한 서비스 안에서 처리하는 금융 플랫폼",
        sector: "핀테크",
        market: "한국",
        period: "2017 - 2020.01",
        status: "아카이브",
        featured: false,
        summary: "대출자와 투자자, 운영팀이 동시에 사용하는 P2P 금융 서비스를 고객 포털과 관리자 시스템으로 나눠 구축한 프로젝트입니다.",
        challenge: "대출 유형별 절차 차이, NICE KYC, 결제 게이트웨이, 법적 안내 페이지, 기존 데이터 이관을 함께 처리해야 했습니다.",
        approach: "Django 기반으로 대출 생성과 심사, 투자 흐름을 위저드 중심으로 재구성하고, 외부 금융 프로바이더와의 통합을 안정적으로 묶었습니다.",
        impactMetrics: ["80+ 데이터 엔티티", "330+ URL 패턴", "4종 대출 유형"],
        stack: ["Python", "Django", "DRF", "MySQL", "jQuery", "AWS S3"],
        highlights: ["NICE KYC 완전 통합", "무중단 데이터 이관", "고객 포털과 관리자 시스템 분리 설계"],
        evidenceNote: "역사적 프로젝트로, market-intel의 case-study와 one-pager를 기준으로 서술했습니다."
    },
    {
        slug: "pilates-app",
        titleKo: "필라테스 프랜차이즈 관리 앱",
        titleEn: "Pilates App",
        tagline: "예약, 결제, CRM, 매출 관리를 하나로 묶은 프랜차이즈 운영 앱",
        sector: "피트니스",
        market: "한국",
        period: "4개월",
        status: "구축 완료",
        featured: false,
        summary: "지점 운영과 회원 관리, 수업 예약, 결제, 커뮤니티를 통합한 프랜차이즈 운영 서비스입니다.",
        challenge: "여러 지점과 강사, 회원의 일정과 결제를 동시에 다루면서 운영자 대시보드까지 함께 설계해야 했습니다.",
        approach: "React Native 기반 멀티플랫폼 전략으로 모바일과 웹을 동시 전개하고, 필라테스 프랜차이즈의 반복 업무를 제품으로 압축했습니다.",
        impactMetrics: ["4개월 개발", "3개 플랫폼 출시", "8개 핵심 기능 모듈"],
        stack: ["React Native", "React", "Node.js", "Android", "iOS", "REST API"],
        highlights: ["다지점 운영 구조", "예약·결제·CRM 통합", "기획·디자인·개발 풀스코프 수행"],
        evidenceNote: "공개 신호 기반 분석 프로젝트로, 포트폴리오 문서에 명시된 범위만 반영했습니다."
    },
    {
        slug: "calendar-share",
        titleKo: "캘린더 쉐어",
        titleEn: "Calendar Share",
        tagline: "소셜 피드와 일정을 결합한 글로벌 캘린더 공유 앱",
        sector: "소셜 플랫폼",
        market: "글로벌",
        period: "2025.01",
        status: "MVP 완료",
        featured: false,
        summary: "소셜 포스트와 캘린더 이벤트를 연결해 바이럴 이벤트 확산을 유도한 모바일 서비스입니다.",
        challenge: "일정 관리 앱의 실용성과 소셜 서비스의 확산성을 동시에 만족시켜야 했고, 적은 리소스로 빠르게 MVP를 완성해야 했습니다.",
        approach: "Flutter 단일 코드베이스와 Firebase/Supabase 조합으로 서버리스 구조를 만들고, QR 기반 관계 형성과 실시간 동기화를 핵심 경험으로 설계했습니다.",
        impactMetrics: ["17,628 LOC", "45+ 화면", "8개 Firebase 서비스"],
        stack: ["Flutter", "Firebase", "Supabase", "Provider", "QR", "Push"],
        highlights: ["좋아요=캘린더 추가 메커니즘", "QR 오프라인 디스커버리", "서버리스 기반 저비용 구조"],
        evidenceNote: "공개 저장소와 market-intel case-study 기준으로 정리했습니다."
    },
    {
        slug: "connectin",
        titleKo: "커넥틴",
        titleEn: "Connectin",
        tagline: "명함 교환을 모바일 네트워킹 서비스로 확장한 B2B 플랫폼",
        sector: "B2B 네트워킹",
        market: "베트남",
        period: "2023.10 - 2025.08",
        status: "휴면",
        featured: false,
        summary: "디지털 명함, 근거리 탐색, 실시간 메시징, OCR 스캔을 결합한 모바일 중심 네트워킹 플랫폼입니다.",
        challenge: "명함이라는 단일 행위를 관계 탐색, 메시징, 기업 네트워킹으로 확장하면서도 모바일 경험을 끊기지 않게 만드는 것이 핵심이었습니다.",
        approach: "Flutter 기반 모바일 앱, Express 백엔드, Next.js 웹을 분리하고, 마이크로서비스와 이중 저장소 구조로 기능별 확장을 가능하게 했습니다.",
        impactMetrics: ["12개 마이크로서비스", "41개 모바일 모듈", "~63개 REST API"],
        stack: ["Flutter", "Next.js", "Express", "PostgreSQL", "Firestore", "Signal Protocol"],
        highlights: ["E2E 암호화 메시징", "BLE + GPS 근거리 탐색", "OCR 명함 스캔과 Zalo 연동"],
        evidenceNote: "베트남 시장 프로젝트로, catalog 기준의 구조와 규모 지표만 노출했습니다."
    },
    {
        slug: "ai-agent",
        titleKo: "AI-네이티브 개발 프레임워크",
        titleEn: "AI-Native Development Framework",
        tagline: "여러 AI 에이전트가 같은 규칙과 품질 게이트로 움직이는 개발 운영체계",
        sector: "AI 툴링",
        market: "글로벌",
        period: "2026.01 - 2026.03",
        status: "내부 프레임워크",
        featured: false,
        summary: "Claude, Gemini, Codex, Jules 같은 서로 다른 에이전트를 공통 규칙과 문서 체계로 통합한 개발 프레임워크입니다.",
        challenge: "에이전트마다 동작 방식이 다르기 때문에 같은 품질 기준, 보안 규칙, 실행 증적을 유지하기가 어렵습니다.",
        approach: "규칙, 페르소나, 스킬, 워크플로우, 런타임 품질 게이트를 모두 코드와 문서 자산으로 구조화해 일관된 SDLC 흐름을 만들었습니다.",
        impactMetrics: ["839개 문서 자산", "134+ 재사용 스킬", "12개 자동 품질 게이트"],
        stack: ["TypeScript", "React", "Hono", "Playwright", "PostgreSQL", "Python"],
        highlights: ["멀티 에이전트 통합 운영", "Tamper detection 기반 품질 게이트", "지식 자산 중심 SDLC 구조"],
        evidenceNote: "내부 프레임워크 사례이며, market-intel의 정량 지표만 외부용으로 정리했습니다."
    },
    {
        slug: "casual-game",
        titleKo: "캐주얼 게임 & 텔레그램 미니앱",
        titleEn: "Casual Game & Telegram Mini-App",
        tagline: "게임, 보상, 커뮤니티 확산을 결합한 Web3 캐주얼 서비스",
        sector: "게임",
        market: "글로벌",
        period: "7개월",
        status: "구축 완료",
        featured: false,
        summary: "HTML5 게임, 텔레그램 미니앱, 백오피스, 레퍼럴 구조를 하나의 Web3 게임 서비스로 엮은 프로젝트입니다.",
        challenge: "가벼운 플레이 경험을 유지하면서도 보상 체계, 초대 구조, 지갑 연동, 운영 툴까지 연결해야 했습니다.",
        approach: "Phaser 게임과 React 프론트, NestJS 백엔드, 텔레그램 통합을 분리해 운영성과 확장성을 확보했습니다.",
        impactMetrics: ["~8,000 LOC", "14개 API", "350+ 커밋"],
        stack: ["Phaser", "React", "NestJS", "MySQL", "Telegram WebApp", "Docker"],
        highlights: ["4개 독립 프론트엔드", "2단계 레퍼럴 시스템", "6개 Docker 서비스 운영"],
        evidenceNote: "게임성과 운영 구조가 함께 드러나는 수치만 선별해 사용했습니다."
    },
    {
        slug: "daystarter",
        titleKo: "데이스타터",
        titleEn: "Daystarter",
        tagline: "기상 행동과 리워드를 결합한 멀티플랫폼 라이프스타일 앱",
        sector: "라이프스타일",
        market: "글로벌",
        period: "2022.06 - 2025.03",
        status: "유지보수",
        featured: false,
        summary: "알람 앱을 넘어 수면 검증, 캐릭터 성장, 토큰 이코노미, 마켓플레이스를 연결한 하이브리드 서비스입니다.",
        challenge: "모바일 습관 형성과 게임적 보상, Web3 개념, 다국어 서비스, 센서 기반 검증 로직을 함께 다뤄야 했습니다.",
        approach: "Android Native와 Flutter, NestJS 백엔드를 조합하고, 수면 검증과 리워드 구조를 서비스 전반에 일관되게 설계했습니다.",
        impactMetrics: ["48개 화면", "37개 데이터 모델", "6개 언어 지원"],
        stack: ["Flutter", "Kotlin", "NestJS", "PostgreSQL", "Redis", "Firebase"],
        highlights: ["센서 기반 수면 검증", "듀얼 토큰 구조", "3플랫폼 동시 운영"],
        evidenceNote: "Daystarter는 별도 marketing-assets catalog와 one-pager를 기준으로 정리했습니다."
    },
    {
        slug: "life3",
        titleKo: "라이프3",
        titleEn: "Life3",
        tagline: "NFT 마켓플레이스와 리워드 시스템을 결합한 Web3 dApp",
        sector: "Web3",
        market: "글로벌",
        period: "2023.12 - 2024.07",
        status: "구축 완료",
        featured: false,
        summary: "NFT 거래, 포인트/토큰 회계, 게이미피케이션, AI 기능을 결합한 복합형 dApp 플랫폼입니다.",
        challenge: "스마트 컨트랙트, 토큰 회계, 관리 콘솔, 게임성, 이벤트성 기능을 동시에 안전하게 설계해야 했습니다.",
        approach: "React·Next.js 프론트와 Express 마이크로서비스, Kafka 이벤트 구조, KMS 서명 체계를 결합해 운영 안정성을 높였습니다.",
        impactMetrics: ["4개 마이크로서비스", "~98개 데이터 모델", "3개 스마트 컨트랙트"],
        stack: ["Next.js", "Express", "PostgreSQL", "Kafka", "Solidity", "AWS KMS"],
        highlights: ["복식부기 포인트/토큰 시스템", "NFT 마켓플레이스 + 에어드롭", "GPT-4o 기반 게임 요소 연동"],
        evidenceNote: "market-intel catalog와 one-pager 기준의 공개 가능한 Web3 지표만 포함했습니다."
    },
    {
        slug: "nft-defi",
        titleKo: "NFT 달팽이 월드 DeFi",
        titleEn: "NFT Snail World DeFi",
        tagline: "수집형 NFT와 DeFi 경제를 결합한 초기 Web3 게임 플랫폼",
        sector: "Web3",
        market: "한국",
        period: "3개월",
        status: "구축 완료",
        featured: false,
        summary: "가챠, 경매, 교환, 스왑, DeFi 루프를 하나의 경제 구조로 엮은 NFT 게임형 플랫폼입니다.",
        challenge: "온체인 자산과 오프체인 포인트를 함께 다루면서도 PC와 모바일 모두에서 접근 가능한 UX를 만들어야 했습니다.",
        approach: "프론트엔드, 백엔드, 스마트 컨트랙트, 블록체인 계층을 나눠 책임을 분리하고, 이중 경제 구조를 서비스 기획의 중심에 두었습니다.",
        impactMetrics: ["6개 기능 모듈", "3개월 구축", "4개 기술 레이어"],
        stack: ["React", "Node.js", "Solidity", "Ethereum", "Klaytn", "Web3"],
        highlights: ["온체인/오프체인 이중 경제", "PC·모바일 반응형 UX", "KLAY/NFT 기반 보상 구조"],
        evidenceNote: "공개 포트폴리오 기반 분석 사례이며, 과장 추정치는 제외했습니다."
    }
];

export const FEATURED_PROJECTS = PROJECTS.filter((project) => project.featured);
